apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eco-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: eco-post.local
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-svc # Le nom du service qu'on a créé juste avant
            port:
              number: 80
